language: python
python: 2.7
env:
  matrix:
   - TOXENV=py27
   - TOXENV=pypy
   - TOXENV=flake8
install:
  - tox
  - if test "$TOXENV" = py27 ; then pip install coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py27 ; then coveralls ; fi
